kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ha-elasticsearch-persistent-volume-claim
  namespace: ha-elasticsearch-cluster
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
