apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-persistent-volume-claim
  namespace: kube-monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
