apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-persistent-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kubernetes/prometheus-persistent-volume"
