apiVersion: v1
kind: Service
metadata: 
  annotations: 
    prometheus.io/scrape: "true"
  name: prometheus-service
  namespace: kube-monitoring
  labels:
    app: prometheus
spec:
  selector: 
    app: prometheus 
  ports: 
    - name: prometheus 
      port: 9090
      targetPort: 9090
