apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus.full_name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "prometheus.release_labels" . | indent 4 }}
