apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: kube-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:6.1.6
        ports:
        - containerPort: 3000
          name: http
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
      initContainers:
      - name: volume-mount-dir-permissions
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /var/lib/grafana"]
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
      serviceAccountName: grafana
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-persistent-volume-claim

