kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-persistent-volume-claim
  namespace: kube-monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
