apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: grafana
  name: grafana
  namespace: kube-monitoring
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: grafana
