apiVersion: v1
kind: Service
metadata:
  name: {{ template "kibana.full_name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kibana.release_labels" . | indent 4 }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: kibana
    port: {{ .Values.containerPort }}
  selector:
    {{- include "kibana.release_labels" . | indent 6 }}
