apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ha-elasticsearch-cluster-role
  namespace: ha-elasticsearch-cluster
rules:
- apiGroups:
  - ""
  resources:
  - deployments
  - statefulsets
  - pods
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
