{
 "title": "Kubernetes Namespace Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "pods",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "volume",
    "label": "PersistentVolumeClaim",
    "query": "label_values(kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=\"$namespace\"}, persistentvolumeclaim)"
   }
  ]
 },
 "panels": [
  {
   "title": "Namespace Based CPU and Ram Usages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Memory Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\", namespace=~\"^$namespace$\", pod_name=~\"^$pod$\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "CPU Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$namespace$\",container_name!=\"POD\", pod_name=~\"^$pod$\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "Disk Usage by Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Persistent Volume Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (\n  container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",container_name!=\"POD\", namespace=~\"^$namespace$\", pod_name=~\"^$pod$\"}\n)\n/\nsum (\n  sum (kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=~\"^$namespace$\", persistentvolumeclaim=~\"^$volume$\"})\n) * 100"
    }
   ]
  },
  {
   "title": "Current Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (\n  container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",container_name!=\"POD\", namespace=~\"^$namespace$\", pod_name=~\"^$pod$\"}\n) by (pod_name, namespace)"
    }
   ]
  },
  {
   "title": "Total Available Disk Size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (\n  sum (kube_persistentvolumeclaim_resource_requests_storage_bytes{namespace=~\"^$namespace$\", persistentvolumeclaim=~\"^$volume$\"})\n) by (persistentvolumeclaim, namespace)"
    }
   ]
  }
 ]
}