# Statefulset metadata & spec
appName: ha-elasticsearch
namespace: ha-elasticsearch-cluster
imageRepository: docker.elastic.co/elasticsearch/elasticsearch-oss
imageTag: 7.0.1
imagePullPolicy: Always
replicas: 5
updateStrategy: RollingUpdate
cpuLimit: 4000m
cpuRequest: 2000m
memoryLimit: "2384Mi"
memoryRequest: "1907Mi"
readinessProbeInitialDelaySeconds: 20
readinessProbePeriodSeconds: 10
livenessProbeInitialDelaySeconds: 20
livenessProbePeriodSeconds: 10

# Service spec
httpRestPort: 9200
transportPort: 9300
serviceType: NodePort

# Elasticsearch options
esJavaOpts: "-Xms2g -Xmx2g"
clusterName: ha-elasticsearch-cluster
nodePrefix: "ha-elasticsearch"
minMasterNodes: 2
vmMaxMapCount: 262144
fileDescriptorLimit: 65535

# Persistency
volumeName: ha-elasticsearch-volume
storageClass: manual
accessMode: ReadWriteOnce
storageResourceRequest: 5Gi

# Pod Disruption Budget
maxUnavailable: 1
pdbName: ha-elasticsearch-pdb
