# Statefulset metadata & spec
appName: ha-elasticsearch
namespace: ha-elasticsearch-cluster
imageRepository: docker.elastic.co/elasticsearch/elasticsearch-oss
imageTag: 7.0.1
imagePullPolicy: Always
replicas: 3
updateStrategy: RollingUpdate
cpuLimit: 2000m
cpuRequest: 1000m
memoryLimit: "4768Mi"
memoryRequest: "3814Mi"
readinessProbeInitialDelaySeconds: 30
readinessProbePeriodSeconds: 10
livenessProbeInitialDelaySeconds: 30
livenessProbePeriodSeconds: 10

# Service spec
httpRestPort: 9200
transportPort: 9300
serviceType: LoadBalancer

# Elasticsearch options
esJavaOpts: "-Xms4g -Xmx4g"
clusterName: ha-elasticsearch-cluster
nodePrefix: "ha-elasticsearch"
minMasterNodes: 2
vmMaxMapCount: 262144
fileDescriptorLimit: 65535

# Persistency
volumeName: ha-elasticsearch-volume
storageClass: do-block-storage
accessMode: ReadWriteOnce
storageResourceRequest: 100Gi

# Pod Disruption Budget
maxUnavailable: 1
pdbName: ha-elasticsearch-pdb
