kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "fluentd.full_name" . }}
roleRef:
  kind: ClusterRole
  name: {{ template "fluentd.full_name" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ template "fluentd.full_name" . }}
  namespace: {{ .Values.namespace }}
