apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kube-state-metrics.full_name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kube-state-metrics.release_labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kube-state-metrics.release_labels" . | indent 6 }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        {{- include "kube-state-metrics.release_labels" . | indent 8 }}
    spec:
      serviceAccountName: kube-state-metrics
      containers:
      - name: kube-state-metrics
        image: {{ .Values.kubeStateMetricsImageRepository }}:{{ .Values.kubeStateMetricsImageTag }}
        imagePullPolicy: {{ .Values.kubeStateMetricsImagePullPolicy }}
        ports:
        - name: http-metrics
          containerPort: {{ .Values.containerHttpMetricsPort }}
        - name: telemetry
          containerPort: {{ .Values.containerTelemetryPort }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.containerHttpMetricsPort }}
          initialDelaySeconds: {{ .Values.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.timeoutSeconds }}
      - name: addon-resizer
        image: {{ .Values.addonResizerImageRepository }}:{{ .Values.addonResizerImageTag }}
        imagePullPolicy: {{ .Values.addonResizerImagePullPolicy }}
        resources:
          limits:
            cpu: {{ .Values.cpuLimit }}
            memory: {{ .Values.memoryLimit }}
          requests:
            cpu: {{ .Values.cpuRequest }}
            memory: {{ .Values.memoryRequest }}
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        command:
          - /pod_nanny
          - --container={{ .Values.appName }}
          - --cpu=100m
          - --extra-cpu=1m
          - --memory=100Mi
          - --extra-memory=2Mi
          - --threshold=5
          - --deployment={{ .Values.appName }}
