apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "kube-state-metrics.full_name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kube-state-metrics.release_labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "kube-state-metrics.full_name" . }}-resizer
subjects:
- kind: ServiceAccount
  name: {{ template "kube-state-metrics.full_name" . }}
  namespace: {{ .Values.namespace }}
