apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "kube-state-metrics.full_name" . }}-resizer
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kube-state-metrics.release_labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs: ["get"]
- apiGroups: ["extensions"]
  resources:
  - deployments
  resourceNames: ["{{ template "kube-state-metrics.full_name" . }}"]
  verbs: ["get", "update"]
