apiVersion: v1
kind: Service
metadata:
  name: {{ template "kube-state-metrics.full_name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kube-state-metrics.release_labels" . | indent 4 }}
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: http-metrics
    port: {{ .Values.containerHttpMetricsPort }}
    targetPort: {{ .Values.containerHttpMetricsPort }}
  - name: telemetry
    port: {{ .Values.containerTelemetryPort }}
    targetPort: {{ .Values.containerTelemetryPort }}
  selector:
    {{- include "kube-state-metrics.release_labels" . | indent 4 }}
