apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kube-state-metrics.full_name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kube-state-metrics.release_labels" . | indent 4 }}
